# Site settings
title: 
header-img: img/home-bg.png
email: rewbal@live.com
copyright_name: gurew86
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gurew86
learn_profile: gurew86
email_username: rewbal@live.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
